# Generated by Django 5.1.1 on 2024-09-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower_flower', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='tg_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
